name: 🏗️ Environment Issue
description: Report issues with environment creation, management, or Python environment problems
title: "[Environment]: "
labels: ["environment", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an environment issue! This template is for issues with Hatch environment creation, management, or Python environment problems.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tried recreating the environment with `--force` flag
          required: true
        - label: I have checked that conda/mamba is properly installed (if using Python environments)
          required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of environment issue are you experiencing?
      options:
        - Environment Creation Failure (cannot create new environment)
        - Environment Removal Issue (cannot remove environment)
        - Environment Switching Issue (cannot switch between environments)
        - Python Environment Issue (conda/mamba environment problems)
        - Environment Corruption (environment exists but is broken)
        - Environment Isolation Issue (packages bleeding between environments)
        - Environment Performance Issue (slow operations, large size)
        - Other
    validations:
      required: true

  - type: input
    id: environment_name
    attributes:
      label: Environment Name
      description: What is the name of the environment?
      placeholder: e.g., my-env, default, test-environment
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Please provide your system details
      placeholder: |
        - OS: (e.g., Ubuntu 22.04, macOS 14.1, Windows 11)
        - Hatch version: (run `pip show hatch`)
        - Python version: 
        - Conda/Mamba version: (run `conda --version` or `mamba --version`)
        - Available disk space: (run `df -h` on Linux/macOS or check disk space on Windows)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: command_run
    attributes:
      label: Command Executed
      description: What exact command did you run?
      placeholder: |
        Paste the exact command that caused the issue:
        hatch env create my-env --python-version 3.11 --description "Test environment"
      render: shell
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: What error message or unexpected output did you receive?
      placeholder: |
        Paste the complete error output here.
        Include the full command output and any error messages.
      render: text
    validations:
      required: true

  - type: textarea
    id: environment_status
    attributes:
      label: Environment Status
      description: |
        Please provide current environment information
      placeholder: |
        Run these commands and paste the output:
        
        hatch env list
        hatch env current
        hatch env python info --hatch_env <env-name> --detailed
        
        For Python environment issues:
        conda env list (or mamba env list)
        conda info (or mamba info)
      render: text
    validations:
      required: true

  - type: textarea
    id: environment_config
    attributes:
      label: Environment Configuration
      description: |
        What configuration was used when creating the environment?
      placeholder: |
        - Python version requested:
        - Description:
        - Special flags used: (--no-python, --no-hatch-mcp-server, etc.)
        - Custom configurations:
      render: text

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: |
        Describe what should happen:
        - Environment should be created successfully
        - Environment should switch without errors
        - Python environment should be accessible
        - etc.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened, including any error messages or unexpected behavior
    validations:
      required: true

  - type: textarea
    id: directory_structure
    attributes:
      label: Directory Structure
      description: |
        If relevant, provide information about the environment directory structure
      placeholder: |
        Environment directory location: ~/.hatch/envs/<env-name>
        
        Directory contents:
        ls -la ~/.hatch/envs/<env-name>/ (Linux/macOS)
        Get-ChildItem ~/.hatch/envs/<env-name>/ (Windows PowerShell)
        
        Python environment location (if applicable):
        conda env list | grep <env-name>
      render: text

  - type: textarea
    id: packages_installed
    attributes:
      label: Packages in Environment
      description: |
        What packages are installed in this environment?
      placeholder: |
        Run and paste output:
        hatch package list --env <env-name>
        
        For Python environment:
        conda list -n <python-env-name> (or mamba list)
      render: text

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds Tried
      description: What have you tried to resolve this issue?
      placeholder: |
        List any workarounds or troubleshooting steps you've tried:
        - Recreating environment with --force
        - Removing and recreating environment
        - Clearing conda/mamba cache
        - Using different Python versions
        - Manual environment cleanup
        - etc.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        Include any additional information:
        - Network connectivity issues during creation
        - Disk space constraints
        - Permission issues
        - Multiple environments with similar issues
        - Custom conda/mamba configurations
        - Related error patterns
